# Word-count ranges
VERY_SHORT_EMAIL_WORDS = 15
QUITE_SHORT_EMAIL_WORDS = 35
DEFAULT_MAX_COLD_EMAIL_WORDS = 160

# Paragraph-related thresholds
SINGLE_PARA_BLOCK_WORDS = 120
WALL_OF_TEXT_PARA_WORDS = 150
MAX_PARAGRAPHS = 6

# Sentence lengths (in words)
AVG_SENT_LONG_THRESHOLD = 25
MAX_SENT_LENGTH_THRESHOLD = 45
CHOPPY_SENT_AVG_THRESHOLD = 7

# Questions / CTA
MAX_QUESTIONS_BEFORE_PENALTY = 4
MAX_CTA_PHRASES_BEFORE_PENALTY = 2

# Subject length (in words)
SUBJECT_SINGLE_WORD_THRESHOLD = 1
SUBJECT_LONG_WORD_THRESHOLD = 8
MIN_SUBJECT_WORDS_FOR_MISMATCH_CHECK = 5

# Layout / skimmability
MAX_LINE_LENGTH_BEFORE_PENALTY = 200
SINGLE_PARA_NO_BREAKS_THRESHOLD = 140

# Cliché penalty cap
MAX_CLICHE_PENALTY = 12.0
CLICHE_PENALTY_PER_HIT = 1.5
