steps:
  - name: gcr.io/cloud-builders/docker
    dir: webapp
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/crm-mvp-481223/default/crm-frontend:latest",
        "-f",
        "Dockerfile.webapp",
        "--build-arg",
        "NEXT_PUBLIC_API_BASE=${_NEXT_PUBLIC_API_BASE}",
        "--build-arg",
        "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}",
        ".",
      ]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "deploy",
        "crm-webapp",
        "--image",
        "us-central1-docker.pkg.dev/crm-mvp-481223/default/crm-frontend:latest",
        "--region",
        "us-central1",
        "--project",
        "crm-mvp-481223",
        "--allow-unauthenticated",
      ]
images:
  - "us-central1-docker.pkg.dev/crm-mvp-481223/default/crm-frontend:latest"
substitutions:
  _NEXT_PUBLIC_API_BASE: ""
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: ""
